# Generated by Django 3.1.5 on 2021-01-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='future',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
