# Generated by Django 3.1.5 on 2021-01-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0005_auto_20210129_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='future',
            name='delta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='future',
            name='gamma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='future',
            name='implied_volatility',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
