# Generated by Django 3.1.5 on 2021-01-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0006_auto_20210129_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='future',
            name='ask',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='future',
            name='bid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
