# Generated by Django 3.1.5 on 2021-01-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0007_auto_20210129_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_a', models.CharField(max_length=50)),
                ('pair_b', models.CharField(max_length=50)),
                ('buy_spread', models.FloatField()),
                ('sell_spread', models.FloatField()),
            ],
        ),
    ]
