# Generated by Django 3.1.5 on 2021-01-31 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0009_spread_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_a', models.CharField(max_length=50)),
                ('pair_b', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='spread',
            name='pair_a',
        ),
        migrations.RemoveField(
            model_name='spread',
            name='pair_b',
        ),
        migrations.AddField(
            model_name='spread',
            name='pair',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='spreads', to='futures.pair'),
            preserve_default=False,
        ),
    ]
