# Generated by Django 3.1.5 on 2021-01-31 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0010_auto_20210131_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='pair_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_pairs', to='futures.future'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='pair_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_pairs', to='futures.future'),
        ),
    ]
